{{- if .Values.sshKeys.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gitsync.sshKeysSecretName" . }}
  labels:
    {{- include "gitsync.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.sshKeys.toolsKeyName | default "id_rsa_1" }}: |
{{- nindent 4 .Values.sshKeys.toolsKey }}
  {{ .Values.sshKeys.wdfKeyName | default "id_rsa_2" }}: |
{{- nindent 4 .Values.sshKeys.wdfKey }}
{{- end }}
