{{- if and .Values.secretEnv.enabled (gt (len .Values.secretEnv.vars) 0) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gitsync.envSecretName" . }}
  labels:
    {{- include "gitsync.labels" . | nindent 4 }}
type: Opaque
stringData:
{{- range $key, $value := .Values.secretEnv.vars }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
{{- end }}
